# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Tulsi Shrivastava
description: >- # this means to ignore newlines until "baseurl:"
  Tulsi Shrivastava Portfolio
baseurl: "/portfolio" # the subpath of the site
url: "https://tulshri.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Academics
    - name: Experience
    - name: Projects
    - name: About Me

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: tshrivas@gmu.edu
      link: mailto:tshrivas@gmu.edu
  follow:
    - name: LinkedIn
      link: www.linkedin.com/in/tulsi-shrivastava-91b558130

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
